<div class="row">
<div class="col-xs-6">
	<img src="images/workshop.jpg" width="95%" height="95%">
</div>
	<div class="col-xs-6 pull-right">
		<?php $this->flash->output() ?>	
		<form method="post" action="workshop/create">
		  <div class="form-group">
		    <label for="name">Workshop naam</label>
		    <input type="text" class="form-control" id="name" name="name" placeholder="Workshop naam" required="required">
		  </div>
		  <div class="form-group">
		    <label for="location">Locatie</label>
		    	<select class="form-control" id="location" name="location">				  
				  <option value="Rotterdam">Rotterdam</option>
				  <option value="Amsterdam">Amsterdam</option>				  
				  <option value="Utrecht">Utrecht</option>
				  <option value="Breda">Breda</option>
				</select>
		  </div> 
		  <div class="form-group">
		    <label for="students">Aantal Deelnemers</label>		    
		    <select class="form-control" name="students">
			  <option value="1">1</option>
			  <option value="2">2</option>
			  <option value="3">3</option>
			  <option value="4">4</option>
			  <option value="5">5</option>
			</select>
		  </div> 
		  <button type="submit" class="btn pull-right btn-primary">Creeren</button>
		</form>
	</div>
</div>
<div class="row">
	<div class="col-xs-12">
	<h1>Workshops lijst</h1>
	<?php if(count($workshops)>0): ?>
		<table class="table"> 
			<thead>	
				<tr> 
					<th>Naam</th>
					<th>Locatie</th>
					<th>Vrije stoelen</th>
					<th>Aantal deelnemers</th>
					<th> </th>
				</tr>
			
			</thead>
			<tbody>
				<?php foreach($workshops as $workshop): ?>					
					<tr>			
						<td><?= $workshop->name; ?></td>
						<td><?= $workshop->location; ?></td>
						<td><?= $workshop->students; ?></td>
						<td><?= count($workshop->student->toArray()); ?></td>
						<td>
							<div class="dropdown">
							  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
							    Dropdown
							    <span class="caret"></span>
							  </button>
							  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">							 
							    <li><a href="workshop/show/<?=$workshop->id?>">Show deelnemers</a></li>
							    <li><a href="workshop/edit/<?=$workshop->id?>">Edit workshop</a></li>
							    <li><a href="workshop/delete/<?=$workshop->id?>">Delete workshop</a></li>
							  </ul>
							</div>
						</td>
					</tr> 				
				<?php endforeach; ?> 
			</tbody>
		</table>
	<?php else: ?>
		<p>Er is geen workshop gevonden ... </p>
	<?php endif; ?>
	</div>
</div>