<div class="row">
<div class="col-xs-6">
	<img src="images/workshop.jpg" width="95%" height="95%">
</div>
	<div class="col-xs-6 pull-right">
		<form>
		  <div class="form-group">
		    <label for="name">Workshop naam</label>
		    <input type="name" class="form-control" id="name" placeholder="Workshop naam">
		  </div>
		  <div class="form-group">
		    <label for="location">Locatie</label>
		    	<select class="form-control">				  
				  <option value="Rotterdam">Rotterdam</option>
				  <option value="Amsterdam">Amsterdam</option>				  
				  <option value="Utrecht">Utrecht</option>
				  <option value="Breda">Breda</option>
				</select>
		  </div> 
		  <div class="form-group">
		    <label for="persons">Aantal Deelnemers</label>
		    <input type="persons" class="form-control" id="persons" placeholder="Maximum Aantal Deelnemers">
		  </div> 
		  <button type="submit" class="btn btn-default pull-right btn-primary">Creeren</button>
		</form>
	</div>
</div>
<div class="row">
	<div class="col-xs-12">
		<table class="table"> 
			<thead>	
				<tr> 
					<th>Workshop</th>
					<th>Locatie</th>
					<th>Aantal deelnemers</th>
					<th> </th>
				</tr>
			
			</thead>
			<tbody>
				<?php foreach($workshops as $workshop): ?>
					<tr>			
						<td><?= $workshop->name; ?></td>
						<td><?= $workshop->location; ?></td>
						<td><?= $workshop->students; ?></td>
						<td>status</td>
					</tr> 
				<?php endforeach; ?> 
			</tbody>
		</table>
	</div>
</div>