<div class="row">
        <div class="col-sm-12 col-md-10 col-md-offset-1">
            <table class="table table-hover" border="1px solid black">

                <thead>
                    <tr>
                        <th>Deelnemers</th>                        
                        <th> </th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>                        
                            <div class="media-body">
                                <h4 class="media-heading">sddfdf</h4>
                            </div>
                        </div></td>                        
                        <td>
                        <button type="button" class="btn btn-danger">
                            <span class="glyphicon glyphicon-remove"></span> Remove
                        </button></td>
                    </tr>                    
                </tbody>
                <tfoot>
                    <tr>                      
                        <td><h5>Workshop Naam<br>Locatie<br>Deelnemers</h5><h3>Vrije plaats</h3></td>
                        <td class="text-right"><h5><strong><?=$workshop->name?><br><?=$workshop->location?><br><?=$workshop->students?></strong></h5><h3><?=$workshop->students - count($workshop->student)?></h3></td>
                    </tr>
                    <tr>                        
                        <td>
                        <button type="button" class="btn btn-default">
                            <span class="glyphicon glyphicon-shopping-cart"></span> Continue Shopping
                        </button></td>
                        <td>
                        <button type="button" class="btn btn-success">
                            Checkout <span class="glyphicon glyphicon-play"></span>
                        </button></td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>