<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="ramsdsal">
    <link rel="icon" href="../../favicon.ico">

    <title>Ramsdsal - Eerst Phalcon project</title>

    <!-- Bootstrap core CSS -->
    <?php $this->assets->outputCss(); ?>    
  </head>

  <body>

    <div class="container">
    	<div class="row">    		
	    	<div class="panel panel-primary">
			  <div class="panel-heading">
			    <h3 class="panel-title"><h3>Phalcon - Workshops management</h3></h3>
			  </div>
			  <div class="panel-body">
			    <?= $this->getContent(); ?>
			  </div>
			</div>			
		</div>	
    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript -->
    <!-- Placed at the end of the document so the pages load faster -->    
    <?php $this->assets->outputJs(); ?>     
  </body>
</html>