<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="ramsdsal">
    <link rel="icon" href="../../favicon.ico">

    <title>Ramsdsal - Eerst Phalcon project</title>

    <!-- Bootstrap core CSS -->
    <?php $this->assets->outputCss(); ?>    
  </head>

  <body>

    <div class="container">
      
	     

    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript -->
    <!-- Placed at the end of the document so the pages load faster -->    
    <?php $this->assets->outputJs(); ?>     
  </body>
</html>